### ISSUE TITLE
这里说的源文件指的是什么呀？【最后将源文件放在resource的指定目录下】谢谢

### ISSUE THREAD

**Issue by 18285160741** [shengjian-tech/opennft#10]
![image](https://user-images.githubusercontent.com/37412616/180178695-435d92bd-7da8-4a5f-94d2-5255728583cf.png)

**Comment by shengjian-tech** [comment]
就是xuperchain的 address 和 private.key 文件

**Comment by 18285160741** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
