### ISSUE TITLE
关于开源版本代码合约及菜单功能等相关疑问

### ISSUE THREAD

**Issue by Ferict** [shengjian-tech/opennft#9]
你好，关于合约部署及配置
```
并完善`nft_chain_plat`,和`nft_user_chainplat`表中的信息
- passwd:安全码,使用SecUtils.encoderByRSAPrivateKey()加密后的数据
- address: 用户超级链的ak地址
- EVMAddress: 使用Account.xchainAKToEVMAddress(address)转换获取
```
能否更加详细的描述一下如何在系统或后台对当前项目的合约进行配置？另外请问合约的开源进行得如何了？是否已经顺利开源？
另外，关于一些功能，如注册用户的相关链数据管理、创建的nft、交易记录等相关后台管理功能是有所缺失还是开源版本不开放？烦请告知。另外支付宝的sdk能否更新到开源版本？

还请解答，谢谢

**Comment by shengjian-tech** [comment]
并完善`nft_chain_plat`,和`nft_user_chainplat`表中的信息
- passwd:安全码,使用SecUtils.encoderByRSAPrivateKey()加密后的数据
- address: 用户超级链的ak地址
- EVMAddress: 使用Account.xchainAKToEVMAddress(address)转换获取
这三个配置项目是手动填入表的,并没有提供界面自动完成.
合约源码预计在8月份开源.
链数据管理、创建的nft、交易记录等相关后台管理功能 开源版本没有完善,希望社区一起共建.
项目中暂时不需要使用支付宝,已经去掉了依赖.
